config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/dashboard' => "dashboard#index", :as => :dashboard
  devise_for :users

  root :to => "welcome#landing"
  resources :questions
  match '/verifyanswer', to: 'questions#submit_answer', via: :post
  match '/clearsession', to: 'questions#clear_session', via: :get
  resources :users
  root :to => redirect('/users'), as: :users_root
  match '/login_create', to: 'sessions#new', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match  '/feedback', to: 'feedback#index', via: :get
  match '/submit_feedback', to: 'feedback#create', via: :post
  match '/show_feedback', to: 'feedback#show', via: :get
  match  '/leaderboard', to: 'leaderboard#index', via: :get
end

app/models/question.rb
# frozen_string_literal: true

##
# This class declares question object model.
class Question < ActiveRecord::Base
  validates :questions, :presence => true
  validates :answer, :presence => true
  validates :option2, :presence => true
  validates :option3, :presence => true
  validates :option4, :presence => true
  validates :explanation, :presence => true
  validates :level, :presence => true
  validate :duplicate_question, on: :create

  def self.create_question!(question, answer, option2, option3, option4, explanation, level)
    @questions = question
    @answer = answer
    @option2 = option2
    @option3 = option3
    @option4 = option4
    @explanation = explanation
    @level = level
    @question = Question::create(questions: @questions, answer: @answer, option2: @option2, option3: @option3, option4: @option4, explanation: @explanation, level: @level)
  end

  def self.verify_answer(checking_array)
    ques = Question.find_by_questions(checking_array[0])
    hash = Hash.new
    hash[:description] = ques.explanation
    hash[:answer] = ques.answer
    if ques.answer == checking_array[1]
      hash[:value] = 'correct'
    else
      hash[:value] = 'incorrect'
    end
    return hash
  end

  def self.calculate_scores(user_id, level)
    @score = User.where(:id => user_id).pluck(:score)
    if level == 'Easy'
      cal_score = @score[0] + 1
    elsif level == 'Medium'
      cal_score = @score[0] + 2
    else
      cal_score = @score[0] + 3
    end
  end

  def duplicate_question
    @question = Question.where('answer LIKE ?', "%#{self.answer}%").pluck(:questions)
    if @question.present?
      @question.each do |que|
        formatted_que = que.inspect.tr('"', '')
        distance = Levenshtein.distance(formatted_que, self.questions)
        percentage_word_similar = compute_similarity(formatted_que, self.questions)
        errors.add(:questions, @message) if distance < 5 || percentage_word_similar > 90
      end
    end
  end

  def compute_similarity(str1, str2)
    str1_split = str1.split(' ')
    str2_split = str2.split(' ')
    intersection = str1_split & str2_split
    min_length_string = (str1_split.length < str2_split.length) ? str1_split : str2_split
    (intersection.length.to_f / min_length_string.length) * 100
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController

  def index
    if params[:rdlevel] != nil
      session[:selected] = params[:rdlevel]
    end
    if session[:count].nil?
      session[:count] = 0
    end
    @ques_opt = []
    if params[:same]== 'yes' and params[:commit]== 'Submit'
      @ques_opt=params[:question]
      if !params[:explanation].nil?
        @exp ='Explanation: ' + params[:explanation]
        @answer = 'Answer: '+ params[:answer]
        @cal_score = params[:score]
      end
    else
      if !user_signed_in?
        session[:count] += 1
        if session[:count] > 10
          flash.now[:notice] = 'Please sign up'
           render "/welcome/landing"
        end
      end
      if session[:selected] == nil
         @questions = Question.pluck(:id,:questions,:answer,:option2,:option3,:option4,:level).sample
      else
         @questions = Question.where(:level => session[:selected]).pluck(:id,:questions,:answer,:option2,:option3,:option4,:level).sample
      end
      if session[:question].blank?
        (session[:question] ||= []) << @questions[1]
      elsif session[:question].include?(@questions[1])
        if session[:selected] == nil
           @new_question = Question.where.not(:questions => session[:question]).pluck(:id,:questions,:answer,:option2,:option3,:option4,:level)
        else
          @new_question = Question.where('questions NOT IN (?) AND level IN (?)', session[:question], session[:selected]).pluck(:id,:questions,:answer,:option2,:option3,:option4,:level)
        end
        if @new_question.empty?
          flash[:notice] = 'No more questions in database'
          render 'welcome/landing'
        else
          session[:question] << @new_question[0][1]
          @questions = @new_question[0]
        end
      else
        session[:question] << @questions[1]
      end
      if current_user
        @score = User.where(:id => current_user.id).pluck(:score)
        @cal_score = @score[0]
      end
      @options = @questions.slice(2..5).shuffle
      @ques_opt << @questions[0] << @questions[1]
      @ques_opt << @options
      @ques_opt << @questions[6]
      @ques_opt.flatten!
    end
  end

  def new
    # render new question page
  end

  def create
    empty_param_hash = {}
    @message = ""
    @que = params[:question]
    if @que.values.any?(&:blank?)
      @que.each do |key, value|
        if @que[key].blank?
          empty_param_hash[key] = value
        end
      end
      if empty_param_hash.length > 1
        @message = 'Sorry, All fields are required'
      else
        @message = empty_param_hash.keys.join == 'level' ? 'Please select a level' : "#{empty_param_hash.keys.join} can't be blank"
      end
      redirect_to new_question_path
    else
      @question = Question.create_question!(@que[:question], @que[:answer], @que[:option2], @que[:option3], @que[:option4], @que[:explanation], @que[:level])
      if @question.save
        flash[:notice] = 'Question successfully added to question bank'
        redirect_to questions_path
      else
        @message = 'Question has already been taken'
        redirect_to new_question_path
      end
    end
    flash[:warning] = @message
  end


  def submit_answer
    @checking_array = []
    @question = params[:question]
    @answer = params[:optradio]
    @checking_array << @question << @answer
    if @checking_array.any? {|a| a.nil?}
      flash[:notice] = 'Please select an answer'
      redirect_to questions_path request.params.merge({same: 'yes'})
    else
      @reply_array = Question.verify_answer(@checking_array)
      if @reply_array[:value] == 'correct'
        if current_user
          @cal_score = Question.calculate_scores(current_user.id, @question[6])
          User.find(current_user.id).update_column(:score, @cal_score)
        end
        flash[:correct] = 'Great! Your answer is correct'
      else
        if current_user
          @score = User.where(:id => current_user.id).pluck(:score)
          @cal_score = @score[0]
        end
        flash[:warning] = 'Sorry, This is the incorrect answer'
      end
       redirect_to questions_path request.params.merge({same: 'yes', explanation: @reply_array[:description], answer: @reply_array[:answer], score: @cal_score})
    end
  end

  def clear_session
    session[:count] = 0
    session[:question] = nil
    session[:selected] = nil
    redirect_to '/'
  end
end

app/views/questions/index.html.erb
<body onload="f()">
<nav class="navbar navbar-expand-lg navbar-light">
  <li class="navbar-brand">WordPower</li>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="navbar-text"><%= "Logged In as  #{current_user.first_name}" %></li>
      <% end %>
      <%= link_to 'Leader board', leaderboard_path, :method => :get, class: "nav-link"%>
      <% if admin? %>
        <%= link_to "Admin Site", rails_admin_path, :method => :get, class: "nav-link" %>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to "Add Feedback",  feedback_path, :method => :get, class: "nav-link" %>
        <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "nav-link"%>
      <% else %>
        <%= link_to "Log in", new_user_session_path, :method => :get, class: "nav-link"%>
      <% end %>
    </ul>
  </div>
</nav>
<div class="container">
  <div class="form-inline" id="question_options">
    <div class ='form-group'>
      <h2 id="difficulty_text"><%= 'Difficulty: ' + @ques_opt[6] %></h2>
    </div>
    <%if user_signed_in? %>
      <%= form_tag questions_path, :method => :get do%>
        <div id="select", class="form-group">
          <ul>
            <li id="option1"><input type="radio" value="<%= "Easy" %>", name="rdlevel"><%= "Easy"%></li>
            <li id="option2"><input type="radio" value="<%= "Medium" %>", name="rdlevel"><%="Medium"%></li>
            <li id="option3"><input type="radio" value="<%= "Hard" %>", name="rdlevel"><%="Hard"%></li>
          </ul>
        </div>
        <div class="form-group">
          <%= submit_tag "Select",class: "btn btn-outline-secondary btn-sm",:id => "select_level", :disabled => true%>
        </div>
      <% end %>
    <% end %>

    <% if user_signed_in? %>
      <div id="score" class="form-group">
        <h3 id="score_text"><%= "Score: #{@cal_score}"%></h3>
      </div>
    <%end %>
  </div>
  <div id="question">
    <h1><%= @ques_opt[1] %></h1>
  </div>

  <%= form_tag verifyanswer_path, :method => :post%>
  <% @ques_opt.each do |e| %>
    <%= hidden_field_tag "question[]", e %>
  <% end %>
  <ul>
    <li id="option"><input type="radio" value="<%= @ques_opt[2] %>", name="optradio"><%= @ques_opt[2] %></li>
    <li id="option"><input type="radio" value="<%= @ques_opt[3] %>", name="optradio"><%= @ques_opt[3] %></li>
    <li id="option"><input type="radio" value="<%= @ques_opt[4] %>", name="optradio"><%= @ques_opt[4] %></li>
    <li id="option"><input type="radio" value="<%= @ques_opt[5] %>", name="optradio"><%= @ques_opt[5] %></li>
  </ul>
  <script>
    function f() {
      var x = document.getElementById("sub");
      if((document.documentElement.textContent && document.documentElement.innerText).indexOf('Explanation:') > -1){
        x.style.display = "none";
      }
    }
  </script>
  <div id="button_bar">
    <%= submit_tag "Submit", class: "btn btn-outline-secondary btn-sm", id:"sub" %>
    <%= link_to "Next", questions_path, :method => :get, class: "btn btn-outline-secondary btn-sm", :id => "next"%>
  </div>

  <br>
  <br>
  <div>
    <% if user_signed_in? %>
      <%= link_to "Add question to the question bank", new_question_path, :method => :get, class: "btn btn-outline-secondary btn-sm", :id=> "add_question"%>
    <% end %>
  </div>
  <div class="explanation" id="explain">
    <%= @exp%>
  </div>
  <div class="answer">
    <%= @answer %>
  </div>
</div>

app/views/questions/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="/">WordPower</a>
  <button class="navbar-toggler btn btn-outline-dark" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="navbar-text"><%= "Logged In as  #{current_user.first_name}" %></li>
      <% end %>
      <% if admin? %>
        <%= link_to "Admin Site", rails_admin_path, :method => :get, class: "nav-link" %>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <%= link_to 'Back to questions', questions_path, :method => :get, class: "nav-link"%>
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "nav-link"%>
      <% else %>
        <%= link_to "Log in", new_user_session_path, :method => :get, class: "nav-link"%>
      <% end %>
    </ul>
  </div>
</nav>
<div  class="container", id="add_form">
  <h1 id="add_title"><b>Add a new question</b></h1>
  <%= form_tag questions_path, method: :post do %>
    <%= label :question, :question,'Question' %>
    <br>
    <%= text_area :question, 'question' %>
    <br>
    <%= label :question, :answer, 'Answer' %>
    <br>
    <%= text_area :question, 'answer' %>
    <br>
    <%= label :question, :option2, 'Option 2' %>
    <br>
    <%= text_area :question, 'option2' %>
    <br>
    <%= label :question, :option3, 'Option 3' %>
    <br>
    <%= text_area :question, 'option3' %>
    <br>
    <%= label :question, :option4, 'Option 4' %>
    <br>
    <%= text_area :question, 'option4' %>
    <br>
    <%= label :question, :explanation, 'Explanation for question' %>
    <br>
    <%= text_area :question, 'explanation' %>
    <br>
    <%= label :question, :level, 'Level of question' %>
    <br>
    <%= select_tag "question[level]", "<option value='Easy'>Easy</option><option value='Medium'>Medium</option><option value='Hard'>Hard</option>", prompt: 'Select Level', class: "btn btn-outline-secondary btn-md"%>
    <br>
    <br>
    <%= submit_tag 'Add this question', class: "btn btn-outline-secondary btn-md" %>
  <%end %>
</div>