config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/dashboard' => "dashboard#index", :as => :dashboard
  devise_for :users

  root :to => "welcome#landing"
  resources :questions
  match '/verifyanswer', to: 'questions#submit_answer', via: :post
  match '/clearsession', to: 'questions#clear_session', via: :get
  resources :users
  root :to => redirect('/users'), as: :users_root
  match '/login_create', to: 'sessions#new', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match  '/feedback', to: 'feedback#index', via: :get
  match '/submit_feedback', to: 'feedback#create', via: :post
  match '/show_feedback', to: 'feedback#show', via: :get
  match  '/leaderboard', to: 'leaderboard#index', via: :get
end

app/models/leaderboard.rb
# frozen_string_literal: true

##
# This class declares leaderboard model.
class Leaderboard

  def self.get_users
    @final_names = []
    @names = User.order(score: :desc).limit(10).pluck(:first_name,:last_name,:score)
    @names.each do |name|
      if name[2] != 0
        full_name = name[0].inspect.gsub('"','') + ' ' + name[1].inspect.gsub('"','')
        @final_names << [full_name, name[2]] unless full_name == 'admin admin'
      end
    end
    return @final_names
  end
end

app/controllers/leaderboard_controller.rb
#frozen_string_literal = true

class LeaderboardController < ApplicationController

  def index
    @top_score = Leaderboard.get_users
  end
end

app/views/leaderboard/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <li class="navbar-brand">WordPower</li>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="navbar-text"><%= "Logged In as  #{current_user.first_name}" %></li>
      <% end %>
      <% if admin? %>
        <%= link_to "Admin Site", rails_admin_path, :method => :get, class: "nav-link" %>
      <% end %>
      <%= link_to 'Back to questions', questions_path, :method => :get, class: "nav-link"%>
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "nav-link"%>
      <% else %>
        <%= link_to "Log in", new_user_session_path, :method => :get, class: "nav-link"%>
      <% end %>
    </ul>
  </div>
</nav>
<h1>Leaderboard</h1>
<div class="container">
  <table class="table table-secondary">
    <thead>
    <tr>
      <th scope="col">#Rank</th>
      <th scope="col">Name</th>
      <th scope="col">Score</th>
    </tr>
    </thead>
    <tbody>
    <% @top_score.each_with_index do |score,index| %>
      <tr>
        <td><%= index+1%></td>
        <td><%=score[0] %></td>
        <td><%= score[1] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>