config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/dashboard' => "dashboard#index", :as => :dashboard
  devise_for :users

  root :to => "welcome#landing"
  resources :questions
  match '/verifyanswer', to: 'questions#submit_answer', via: :post
  match '/clearsession', to: 'questions#clear_session', via: :get
  resources :users
  root :to => redirect('/users'), as: :users_root
  match '/login_create', to: 'sessions#new', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match  '/feedback', to: 'feedback#index', via: :get
  match '/submit_feedback', to: 'feedback#create', via: :post
  match '/show_feedback', to: 'feedback#show', via: :get
  match  '/leaderboard', to: 'leaderboard#index', via: :get
end

app/models/feedback.rb
##
# This class declares feedback model.

class Feedback < ActiveRecord::Base
  belongs_to :user
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  def index
  end

  def create
    @feedback = params[:feedback]['feedback']
    @rating = params[:rate]
    if  @rating.nil?
      flash[:notice] = 'You need to give us the rating'
      redirect_to feedback_path
    else
      current_user.feedbacks.create(feedback_text: @feedback, rating: @rating)
      flash[:notice] = 'Your feedback has been recorded!'
      redirect_to questions_path
    end
  end

  def show
    if current_user.admin == true
      @feedback_data = Feedback.joins(:user).pluck(:feedback_text, :first_name, :last_name, :created_at, :rating)
                         .map{|e| [e[0], e[1] + " " + e[2], e[3].strftime("%F"), e[4]]}
    else
      @feedback_data = Feedback.joins(:user).where("admin = 'f'").pluck(:feedback_text, :first_name, :last_name, :created_at, :rating)
                         .map{|e| [e[0], e[1] + " " + e[2], e[3].strftime("%F"), e[4]]}
    end
    render :partial => 'show' and return if request.xhr?
  end
end

app/views/feedback/_show.html.erb
<table class="table table-light">
  <thead>
  <tr>
    <th scope="col">Date</th>
    <th scope="col">Name</th>
    <th scope="col">Comment</th>
    <th scope="col">Rate</th>
  </tr>
  </thead>
  <tbody>
  <% @feedback_data.each do |e| %>
    <tr>
      <td><%= e[2] %></td>
      <td><%= e[1]%></td>
      <td><%= e[0] %></td>
      <td><%= e[3] %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Close',feedback_path, :id => "closeLink" %>

app/views/feedback/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <li class="navbar-brand">WordPower</li>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="navbar-text"><%= "Logged In as  #{current_user.first_name}" %></li>
      <% end %>
      <% if admin? %>
        <%= link_to "Admin Site", rails_admin_path, :method => :get, class: "nav-link" %>
      <% end %>
      <%= link_to 'Back to questions', questions_path, :method => :get, class: "nav-link"%>
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "nav-link"%>
      <% else %>
        <%= link_to "Log in", new_user_session_path, :method => :get, class: "nav-link"%>
      <% end %>
    </ul>
  </div>
</nav>

<div  class="container", id="add_form">
  <h1 id="add_title"><b>Give us your feedback</b></h1> <br><br>
  <%= form_tag submit_feedback_path, method: :post do %>
    <h3>How is your experience with our site?</h3>
    <div class="rate">
      <input type="radio" id="star5" name="rate" value="5" />
      <label for="star5" title="text">5 stars</label>
      <input type="radio" id="star4" name="rate" value="4" />
      <label for="star4" title="text">4 stars</label>
      <input type="radio" id="star3" name="rate" value="3" />
      <label for="star3" title="text">3 stars</label>
      <input type="radio" id="star2" name="rate" value="2" />
      <label for="star2" title="text">2 stars</label>
      <input type="radio" id="star1" name="rate" value="1" />
      <label for="star1" title="text">1 star</label>
    </div>
    <br>
    <br>
    <h3>Additional comment</h3>
    <br>
    <%= text_area :feedback, 'feedback', id: "feedback_text", :placeholder => 'Optional' %>
    <br>
    <br>
    <%= submit_tag 'Submit', class: "btn btn-outline-secondary btn-md" %>
    <%= link_to "Show Feedback", show_feedback_path, :method => :get, class: "btn btn-outline-secondary btn-sm", :id => "showfeedback", remote: true%>
  <%end %>
</div>
<div class="container">
  <div id="showFeedback">

  </div>
</div>

app/views/feedback/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <li class="navbar-brand">WordPower</li>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="navbar-text"><%= "Logged In as  #{current_user.first_name}" %></li>
      <% end %>
      <% if admin? %>
        <%= link_to "Admin Site", rails_admin_path, :method => :get, class: "nav-link" %>
      <% end %>
      <%= link_to 'Back to questions', questions_path, :method => :get, class: "nav-link"%>
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "nav-link"%>
      <% else %>
        <%= link_to "Log in", new_user_session_path, :method => :get, class: "nav-link"%>
      <% end %>
    </ul>
  </div>
</nav>
<h1>Feedback</h1>
<div class="container", id="feedback_info">
  <table class="table table-light">
    <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Name</th>
      <th scope="col">Comment</th>
      <th scope="col">Rate</th>
    </tr>
    </thead>
    <tbody>
      <% @feedback_data.each do |e| %>
        <tr>
          <td><%= e[2] %></td>
          <td><%= e[1]%></td>
          <td><%= e[0] %></td>
          <td><%= e[3] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Back", :back, class: "btn btn-outline-secondary btn-sm"%>
</div>